.TH BSEARCH 1 "2018 March 10" "bsearch"

.SH NAME
bsearch - A utility for binary searching a sorted file for lines that start with the search key.

.SH SYNOPSIS
.B bsearch
.I SEARCH_KEY
.I FILENAME

.SH DESCRIPTION
.B bsearch
is a utility for binary searching a sorted file for lines that start with the search key.

.SH AUTHORS
.B bsearch
was written by
.MT myself@james-ridgway.co.uk
James Ridgway
.ME .